# Generated by Django 5.2.6 on 2025-09-04 16:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acomodacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('ocupado', 'Ocupado'), ('manutencao', 'Em Manutenção'), ('limpeza', 'Limpeza')], default='disponivel', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('cpf', models.CharField(help_text='Formato: 000.000.000-00', max_length=14, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Hotel/Pousada', max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Dinheiro, Cartão de Crédito, PIX', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAcomodacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Suíte Master, Quarto Simples', max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frigobar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acomodacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frigobar', to='gestao.acomodacao')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFrigobar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('frigobar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.frigobar')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.itemestoque')),
            ],
        ),
        migrations.AddField(
            model_name='frigobar',
            name='itens',
            field=models.ManyToManyField(through='gestao.ItemFrigobar', to='gestao.itemestoque'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_checkin', models.DateField()),
                ('data_checkout', models.DateField()),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('confirmada', 'Confirmada'), ('checkin', 'Check-in Realizado'), ('checkout', 'Check-out Realizado'), ('cancelada', 'Cancelada')], default='confirmada', max_length=20)),
                ('valor_total_diarias', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_consumo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_extra', models.DecimalField(decimal_places=2, default=0.0, help_text='Taxas ou valores adicionais.', max_digits=10)),
                ('valor_total_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('acomodacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='gestao.acomodacao')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='gestao.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.formapagamento')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='gestao.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, help_text='Preço do item no momento do consumo', max_digits=10)),
                ('data_consumo', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.itemestoque')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='gestao.reserva')),
            ],
        ),
        migrations.AddField(
            model_name='acomodacao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.tipoacomodacao'),
        ),
        migrations.CreateModel(
            name='VagaEstacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vaga', models.CharField(max_length=10, unique=True)),
                ('disponivel', models.BooleanField(default=True)),
                ('acomodacao_vinculada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.acomodacao')),
            ],
        ),
    ]
