# Generated by Django 5.2.6 on 2025-09-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acomodacao',
            name='capacidade',
            field=models.PositiveIntegerField(default=1, help_text='Número máximo de hóspedes.'),
        ),
        migrations.AddField(
            model_name='acomodacao',
            name='qtd_camas',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade de camas no quarto.'),
        ),
    ]
