# Generated by Django 5.2.6 on 2025-09-09 13:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_gastocategoria_gasto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Alimentação, Limpeza, Manutenção', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria de Gasto',
                'verbose_name_plural': 'Categorias de Gastos',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='acomodacao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acomodacoes', to='gestao.tipoacomodacao'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='data_gasto',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
