# Generated by Django 5.2.6 on 2025-09-09 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_categoriagasto_alter_acomodacao_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='gestao.categoriagasto'),
        ),
        migrations.DeleteModel(
            name='GastoCategoria',
        ),
    ]
