# Generated by Django 5.2.6 on 2025-09-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_alter_gasto_categoria_delete_gastocategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='num_adultos',
            field=models.PositiveIntegerField(default=1, help_text='Número de adultos'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='num_criancas_12',
            field=models.PositiveIntegerField(default=0, help_text='Crianças de 6 a 12 anos'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='num_criancas_5',
            field=models.PositiveIntegerField(default=0, help_text='Crianças até 5 anos'),
        ),
    ]
