# Generated by Django 5.2.6 on 2025-09-18 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_cria_superusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, help_text='Formato: 00000-000', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua/Logradouro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='num_adultos',
            field=models.PositiveIntegerField(default=1, help_text='N° de adultos', verbose_name='N° Adultos'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='num_criancas_12',
            field=models.PositiveIntegerField(default=0, help_text='Crianças de 6 a 12 anos', verbose_name='N° Crianças de 6 a 12 anos'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='num_criancas_5',
            field=models.PositiveIntegerField(default=0, help_text='Crianças até 5 anos', verbose_name='N° Crianças até 5 anos'),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda'),
        ),
        migrations.CreateModel(
            name='ArquivoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='arquivos_reservas/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='gestao.reserva')),
            ],
        ),
    ]
