# Generated by Django 5.2.6 on 2025-09-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_cliente_bairro_cliente_cep_cliente_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='clientes_fotos/', verbose_name='Foto do Cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('pre_reserva', 'Pré-reserva'), ('confirmada', 'Confirmada'), ('checkin', 'Check-in Realizado'), ('checkout', 'Check-out Realizado'), ('cancelada', 'Cancelada')], default='pre_reserva', max_length=20),
        ),
    ]
