# Generated by Django 5.2.6 on 2025-09-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_alter_itemestoque_preco_venda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('pre_reserva', 'Pré-reserva'), ('confirmada', 'Confirmada'), ('checkin', 'Check-in Realizado'), ('checkout', 'Check-out Realizado'), ('cancelada', 'Cancelada')], default='pre_reserva', max_length=20),
        ),
    ]
