# Generated by Django 5.2.6 on 2025-09-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_alter_reserva_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='clientes_fotos/', verbose_name='Foto do Cliente'),
        ),
    ]
