# Generated by Django 5.2.6 on 2025-09-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_alter_acomodacao_id_alter_arquivoreserva_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, max_length=50000, null=True, upload_to='clientes_fotos/', verbose_name='Foto do Cliente'),
        ),
    ]
