# Generated by Django 5.2.6 on 2025-10-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0011_alter_cliente_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, max_length=100000, null=True, upload_to='clientes_fotos/', verbose_name='Foto do Cliente'),
        ),
    ]
