# Generated by Django 5.2.6 on 2025-10-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0012_alter_cliente_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Foto do Cliente'),
        ),
    ]
