# Generated by Django 5.2.6 on 2025-10-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0012_alter_reserva_data_checkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemestoque',
            name='is_frigobar',
            field=models.BooleanField(default=False, verbose_name='É item de frigobar?'),
        ),
    ]
