# Generated by Django 5.2.6 on 2025-10-08 12:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0013_itemestoque_is_frigobar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemestoque',
            name='is_frigobar',
        ),
        migrations.CreateModel(
            name='CompraEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_compra_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Custo (Unitário)')),
                ('fornecedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fornecedor/Local da Compra')),
                ('data_compra', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='gestao.itemestoque')),
            ],
        ),
    ]
