# Generated by Django 5.2.6 on 2025-10-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0013_alter_cliente_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='placa_automovel',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Placa do Automóvel'),
        ),
    ]
