# Generated by Django 5.2.6 on 2025-10-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0014_reserva_placa_automovel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_checkin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_checkout',
            field=models.DateTimeField(),
        ),
    ]
