# Generated by Django 5.2.6 on 2025-10-08 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0014_remove_itemestoque_is_frigobar_compraestoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraDeTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_regra', models.CharField(choices=[('diaria', 'Diária'), ('pacote', 'Pacote'), ('acrescimo_pessoa', 'Acréscimo por Pessoa Extra')], default='diaria', max_length=20)),
                ('periodo', models.CharField(choices=[('semana', 'Dia de Semana'), ('fim_de_semana', 'Fim de Semana')], max_length=20)),
                ('num_pessoas', models.PositiveIntegerField(default=1, help_text="Número de pessoas para esta tarifa. Use 0 para 'por pessoa'.")),
                ('num_diarias', models.PositiveIntegerField(default=1, help_text='Número de diárias (para pacotes). Use 1 para diárias normais.')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_acomodacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_tarifa', to='gestao.tipoacomodacao')),
            ],
            options={
                'verbose_name': 'Regra de Tarifa',
                'verbose_name_plural': 'Regras de Tarifa',
            },
        ),
    ]
