# Generated by Django 5.2.6 on 2025-10-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0015_regradetarifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoacomodacao',
            name='chave_de_preco',
            field=models.CharField(default='', help_text="Chave usada pela calculadora de tarifas (ex: 'quarto', 'chale', 'coletivo', 'quarto_familia'). Use apenas letras minúsculas e sem espaços.", max_length=50),
            preserve_default=False,
        ),
    ]
