# Generated by Django 5.2.6 on 2025-10-09 22:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0015_alter_reserva_data_checkin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acomodacao',
            name='valor_diaria',
        ),
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tipoacomodacao',
            name='chave_de_preco',
            field=models.CharField(default='', help_text="Chave usada pela calculadora de tarifas (ex: 'quarto', 'chale', 'coletivo', 'quarto_familia'). Use apenas letras minúsculas e sem espaços.", max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CompraEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_compra_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Custo (Unitário)')),
                ('fornecedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fornecedor/Local da Compra')),
                ('data_compra', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='gestao.itemestoque')),
            ],
        ),
    ]
