# Generated by Django 5.2.6 on 2025-10-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0016_tipoacomodacao_chave_de_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acomodacao',
            name='valor_diaria',
        ),
    ]
