# Generated by Django 5.2.6 on 2025-10-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0017_remove_acomodacao_valor_diaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True),
        ),
    ]
