# Generated by Django 5.2.6 on 2025-10-09 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0019_alter_cliente_sexo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegraDeTarifa',
        ),
    ]
